// <auto-generated />
namespace ModuleZeroSampleProject.Migrations.App
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateConfigurationModuleZeroSample : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateConfigurationModuleZeroSample));
        
        string IMigrationMetadata.Id
        {
            get { return "201504221236306_UpdateConfigurationModuleZeroSample"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
